import './normalize.css'
import './fonts.css'
import './globals.css'
import './variables.css'

import './components/_header.css'
import './components/_body.css'
import './components/_newItems.css'
import './components/_filmCard.css'
import './components/_loader.css'
import './components/_filmpage.css'
import './components/_features.css'
import './components/_search.css'
import './components/_movieslist.css'